# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

- script: |
    pip install pyang
  displayName: 'Install prerequisites'

- script: |
    pyang -version
  displayName: 'Get pyang version'

- script: |
    pyang *.yang
  displayName: 'Get pyang version'


