# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    pip install pyang
    pyang $(Build.SourcesDirectory)/Common/*.yang
    pyang $(Build.SourcesDirectory)/Device/*.yang -p ../Common
    pyang $(Build.SourcesDirectory)/Network/*.yang -p ../Common
    pyang $(Build.SourcesDirectory)/Service/*.yang -p ../Common
  displayName: 'Run a multi-line script'
